# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  ## GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      # group patch updates
      all:
        update-types: [ patch, minor, major ]

  ## Go
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        update-types: [ patch, minor ]
