name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:

  label:
    name: Label PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    steps:
    - uses: actions/labeler@v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  add-to-project:
    name: Add to Triage Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/smallstep/projects/94
          github-token: ${{ secrets.TRIAGE_PAT }}
